---
title: "User music app behaivor"
author: "Manuel Lagunas"
format: 
    html:
        toc: true
editor: visual
jupyter: python3
---

# Introducción
En este proyecto, compara las preferencias musicales de las ciudades de Springfield y Shelbyville. Estudiando datos reales de transmisión de música online para probar las hipótesis a continuación plateadas y comparar el comportamiento de los usuarios y las usuarias de estas dos ciudades.

## Objetivo
Prueba tres hipótesis:
- La actividad de los usuarios y las usuarias difiere según el día de la semana y dependiendo de la cuidad.
- Los lunes por la mañana, los habitantes de Springfield y Shelbyville escuchan géneros distintos. Lo mismo ocurre con los viernes por la noche.
- Los oyentes de Springfield y Shelbyville tienen preferencias distintas. En Springfield prefieren el pop, mientras que en Shelbyville hay más personas a las que les gusta el rap.

## Etapas
El proyecto consistirá en tres etapas:
- Descripción de los datos
- Preprocesamiento de datos
- Prueba de hipótesis


# Exploration data alalysis

## Librerias
```{python}
import pandas as pd
```


## Lectura de datos
```{python}
df_raw = pd.read_csv("files/datasets/input/music_project_en.csv")
```

## Exploración de datos
```{python}
# Basic exploration
print(df_raw.sample(10))
print()
print(df_raw.shape)
print()
print(df_raw.info())
print()
print(df_raw.describe())
```

```{python}
# Null values
print(df_raw.isnull().sum())
print()
print((df_raw.isnull().sum() / len(df_raw)) * 100)
```

```{python}
# duplicate values
df_raw.duplicated().sum()
```

## Conclusiones
* Podemos ver tres problemas con el estilo en los encabezados de la tabla:
  - Algunos encabezados están en mayúsculas, otros, en minúsculas.
  - Hay espacios en algunos encabezados.
  - Algunos nombres no son descriptivos al contenido de los datos.

* Las filas describen las canciones que una determinada usuaria o usuario escuchó durante un día y hora especifico. Entender lo que almacenan las columnas, es posible mediante el estudio de las celdas de las columnas, de surguir alguna duda, seria importante platicar con quien estuvo recopilando los datos o consultar alguna documentación que exista al respecto

* Contamos con los datos suficientes para probar la hipótesis: La primera hipótesis podria ser contestada con las columnas userID, City y Day La segunda hipótesis podria ser contestada con las columnas City, genre, time y Day La tercera hipóteis podria ser contestada con las columnas City y genre Por tanto Se considera que es posible confirmar y rechazar las hipótesis con los datos disponibles
  
* La información general del Dataframe indica que existen valores ausentes en los datos, los duplicados no son perseptibles en las primeras díes filas del Datafreme, sin embargo se debe de realizar un analisis para poder detectar alguno. Todos los datos son de tipo object

* No todos los valores ausentes afectan a la investigación. Por ejemplo, los valores ausentes en track y artist no son cruciales. Simplemente se pueden reemplazar con valores predeterminados como el string 'unknown' (desconocido). Pero los valores ausentes en 'genre' pueden afectar la comparación entre las preferencias musicales de Springfield y Shelbyville. En la vida real, sería útil saber las razones por las cuales hay datos ausentes e intentar recuperarlos. Pero no tenemos esa oportunidad en este proyecto por lo que tambien los valores ausentes serán sustituidos por el string 'unknown'

* Despues de eliminar los datos duplicados explicitos se debe realizar un estudio para saber si existe algun duplicado implicito

# Preprocesamiento de datos

```{python}
# Columns name
print(df_raw.columns)

def convert_to_snake_case(df):
    df.columns = df.columns.str.strip().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('-', '_').str.lower()
    return df

df = convert_to_snake_case(df_raw)

print(df.columns)
```

```{python}
# Fixing null values
df[['track', 'artist', 'genre']] = df[['track', 'artist', 'genre']].fillna('unknown') 

print(df.isna().sum())
```

```{python}
# Duplicated data
df=df.drop_duplicates().reset_index(drop=True)
print(df.duplicated().sum())
```

```{python}
# Non explicit duplicated data
print(sorted(df['genre'].unique()))
```

## Conclusión
Se observan los siguientes duplicados implícitos:
- hip
- hop
- hip-hop
Se cambiaran por el nombre hip-hop

```{python}
df['genre'] = df['genre'].replace(['hip', 'hop', 'hip-hop'], 'hiphop')
print(sorted(df['genre'].unique()))
```

## Conclusiones de la etapa
* Se solucionaron los problemas detectados en el apartado de descripción de los datos
* En cuanto al estudio de duplicados implicitos. Se pasaron de 269 valores unicos en la columna 'genre', a 266. Indicador de que se logro depurar los valores duplicados implícitos de los valores unicos de 'genre'.

# Prueba de hipotesis
## Primera hipotesis
La primera hipótesis afirma que existen diferencias en la forma en que los usuarios y las usuarias de Springfield y Shelbyville consumen música. Para comprobar esto, usa los datos de tres días de la semana: lunes, miércoles y viernes.

```{python}
#  plays by city
group_by_city_tracknumbers=df.groupby(by='city')['track'].count()
print(group_by_city_tracknumbers)
```

### Observación
La ciudad de Sprinfield escucha mas del doble de canciones que la ciudad de Shelbyville

```{python}
# plays by day of the week
group_by_day_tracknumbers=df.groupby(by='day')['track'].count()
print(group_by_day_tracknumbers)
```

### Observación
Los días lunes y viernes se escuchan casi el mismo número de canciones presentando una baja en la escucha el día miercoles

```{python}
# study function
def number_tracks(day,city):
    track_list=df[(df['day']==day) & (df['city']==city)]
    track_list_count = track_list['userid'].count()
    return track_list_count
```

```{python}
# calculation
springfield_monday = number_tracks('Monday','Springfield')
print(springfield_monday)

shelbyville_monday = number_tracks('Monday','Shelbyville')
print(shelbyville_monday)

springfield_wednesday = number_tracks('Wednesday','Springfield')
print(springfield_wednesday)

shelbyville_wednesday = number_tracks('Wednesday','Shelbyville')
print(shelbyville_wednesday)

springfield_friday = number_tracks('Friday','Springfield')
print(springfield_friday)

shelbyville_friday = number_tracks('Friday','Shelbyville')
print(shelbyville_friday)
```

```{python]
# Results table
headers=['ciy','monday','wednesday','friday']
results_day_city=[
                 ['Springfield',springfield_monday,springfield_wednesday,springfield_friday],
                 ['Shelbyville',shelbyville_monday,shelbyville_wednesday,shelbyville_friday]
]
df_day_city=pd.DataFrame(data=results_day_city, columns=headers)
print(df_day_city)
```

## Conclusión de la primera hipotesis
* La primera hipótesis el la siguiente: La actividad de los usuarios y las usuarias difiere según el día de la semana y dependiendo de la cuidad. Para confirmarse o negarse la hipótesis se creo el Dataframe de nombre df_day_city del cual podemos concluir lo siguiente:

  - 1.Los usuarios de Spingfield escuchas mas canciones en todos los días de la semana que los usuarios de Shelbyville según los valores absolutos. Sin embargo de acuerdo a los porentajes se ven diferencias de aproximadamente un digito siendo los días lunes y viernes de mayor escucha en Springfield que en Shelbyville, solo presentandose el caso de ser mayores los oyenetes según porcentajes en Shelbyville que en Springfield

  - 2.En Sprinfield se observa que los días Lunes y viernes se escuchan casi el mismo número de canciones obsrvandose un aumento marginal el día viernes respecto al lunes y decayendo el día miercoles considerablemente

  - 3.Caso contrario en Shelbyville, donde se observa el mismo comportamiento que Springfield los días Lunes y viernes que se mantienen constantes con un aumento marginal el día viernes respecto al lunes pero siendo el día miercoles el día en que mas escuchan música los usuarios de Shelbyville.

* Por lo que podemos decir que la hipotesis es confirmada parcialmente. Siendo correcta si hablamos del día miercoles,donde en una ciudad se ve una disminución y en la otra un aumento; E incorrecta los días lunes y viernes ya que se observa el mismo comportamiento en ambas ciudades, donde solo hay un aumento marginal de canciones escuchadas el día viernes respecto al lunes.

## Segunda hipotesis
Según la segunda hipótesis, el lunes por la mañana y el viernes por la noche, los ciudadanos de Springfield escuchan géneros que difieren de los que disfrutan los usuarios de Shelbyville.

```{python}
#cities separation
spr_general=df[df['city']=='Springfield']
print(spr_general)
print()

shel_general=df[df['city']=='Shelbyville']
print(shel_general)
```

```{python}
#study function
def genre_weekday(df,day,time1,time2):
    genre_df = df[(df['day']==day) & (df['time']<time2) & (df['time']>time1)]
    genre_df_count = genre_df.groupby('genre')['genre'].count()
    genre_df_sorted = genre_df_count.sort_values(ascending=False)
    return genre_df_sorted[:15]
```

```{python}
# calculations
spr_mond_mor=genre_weekday(spr_general,'Monday','07:00:00','11:00:00')
print(spr_mond_mor)
print()

shel_mond_mor=genre_weekday(shel_general,'Monday','07:00:00','11:00:00')
print(shel_mond_mor)
print()

spr_frid_eve=genre_weekday(spr_general,'Friday','17:00:00','23:00:00')
print(spr_frid_eve)
print()

shel_frid_eve=genre_weekday(shel_general,'Friday','17:00:00','23:00:00')
print(shel_frid_eve)
```

## Conclusión de la segunda hipotesis
* La segunda hipótesis a estudiar es: Los lunes por la mañana, los habitantes de Springfield y Shelbyville escuchan géneros distintos. Lo mismo ocurre con los viernes por la noche Según los resultados obtenidos por el segundo estudio de los datos podemos concluir que:

* Aunque los generos no aparecen en el mismo orden, ambas ciudades escuchan los mismos generos los días lunes por la mañana, existiendo diferencias minimas sobre los generos que cada ciudad escucha.
  
* De igual manera. Aunque si bien no aparecen en el mismo orden podemos ver que los viernes por la tarde los usuarios de ambas ciudades escuchan los mismos 15 generos musicales
  
* Por tanto podemos decir que la hipótesis planteadea es incorrecta, ya que los datos indican que ambas ciudades gustan de escuchar los mismos generos.

## Tercera hipotesis
Hipótesis: Shelbyville ama la música rap. A los residentes de Springfield les gusta más el pop.

```{python}
#study table
spr_genres=spr_general.groupby('genre')['genre'].count()
spr_genres=spr_genres.sort_values(ascending=False)
print(spr_genres.head(10))
```

```{python}
#study table
shel_genres=shel_general.groupby('genre')['genre'].count()
shel_genres=shel_genres.sort_values(ascending=False)
print(shel_genres.head(10))
```

## Conclusión de la tercera hipotesis
La tercera hipótesis a comprobar es: Los oyentes de Springfield y Shelbyville tienen preferencias distintas. En Springfield prefieren el pop, mientras que en Shelbyville hay más personas a las que les gusta el rap.

* De acuerdo con los resultados obtenidos podemos decir que la hipótesis es parcialmente correcta ya que:
* El primer lugar de ambas ciudades, es el genero pop, por lo que la hipotesis es correcta en el caso de Springfield e incorrecta en el caso de Shelbyville que aseguraba que el genero preferido era rap
* El genero rap no aparece como de los mas escuchados en la lista del top 10 de Shelbyville concluyendo entonces que la segunda parte de la hipótesis es incorrecta.

# Conclusiones
* 1.La actividad de los usuarios y las usuarias difiere según el día de la semana y dependiendo de la cuidad. Es correcta parcialmente, ya que en ambas ciudades de observo el mismo comportamiento los días lunes y viernes observandose un cambio significativo solo los días miercoles.

* 2.Los lunes por la mañana, los habitantes de Springfield y Shelbyville escuchan géneros distintos. Lo mismo ocurre con los viernes por la noche. Los resultados arrojaron que ambas ciudades escuchan los mismos generos en ambos días y momentos por lo que la hipótesis es incorrecta.

* 3.Los oyentes de Springfield y Shelbyville tienen preferencias distintas. En Springfield prefieren el pop, mientras que en Shelbyville hay más personas a las que les gusta el rap. La hipotesis es parcialmente correcta, ya que ambos gustan del pop como genero principal

## Por tomar en cuenta
En proyectos de investigación reales, la prueba de hipótesis estadística es más precisa y cuantitativa. También se debe tomar en cuenta que no siempre se pueden sacar conclusiones sobre una ciudad entera a partir de datos de una sola fuente.


